In [ ]:
# step 1: importing packages
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split # to split the dataset into training and test dataset
from sklearn import preprocessing # used for feature scaling

In [ ]:
# reading dataset or loading the dataset
df = pd.read_csv('/content/drive/MyDrive/deep_learning_bootcamp/housepricedata.csv')

In [ ]:
# displaying the dataset 
df

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
# checking the shape(no of rows and column) of the dataset
df.shape

(1460, 11)

In [ ]:
# checking the number of columns in the dataset
df.columns

Index(['LotArea', 'OverallQual', 'OverallCond', 'TotalBsmtSF', 'FullBath',
       'HalfBath', 'BedroomAbvGr', 'TotRmsAbvGrd', 'Fireplaces', 'GarageArea',
       'AboveMedianPrice'],
      dtype='object')

In [ ]:
# checking the type of df
type(df)

pandas.core.frame.DataFrame

In [ ]:
# checking the information of the column
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   LotArea           1460 non-null   int64
 1   OverallQual       1460 non-null   int64
 2   OverallCond       1460 non-null   int64
 3   TotalBsmtSF       1460 non-null   int64
 4   FullBath          1460 non-null   int64
 5   HalfBath          1460 non-null   int64
 6   BedroomAbvGr      1460 non-null   int64
 7   TotRmsAbvGrd      1460 non-null   int64
 8   Fireplaces        1460 non-null   int64
 9   GarageArea        1460 non-null   int64
 10  AboveMedianPrice  1460 non-null   int64
dtypes: int64(11)
memory usage: 125.6 KB


In [ ]:
# printing first 5 rows in a dataset
df.head() # argument = no of rows to be displayed

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0     8450            7            5          856         2         1   
1     9600            6            8         1262         2         0   
2    11250            7            5          920         2         1   
3     9550            7            5          756         1         0   
4    14260            8            5         1145         2         1   

   BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0             3             8           0         548                 1  
1             3             6           1         460                 1  
2             3             6           1         608                 1  
3             3             7           1         642                 0  
4             4             9           1         836                 1

In [ ]:
# printing last 5 rows in a datase
df.tail() 

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0

In [ ]:
# printing specific value
# iloc refer to integer location
df.iloc[5,10]

0

In [ ]:
# generate descriptive statistics
df.describe()

LotArea  OverallQual  OverallCond  TotalBsmtSF     FullBath  \
count    1460.000000  1460.000000  1460.000000  1460.000000  1460.000000   
mean    10516.828082     6.099315     5.575342  1057.429452     1.565068   
std      9981.264932     1.382997     1.112799   438.705324     0.550916   
min      1300.000000     1.000000     1.000000     0.000000     0.000000   
25%      7553.500000     5.000000     5.000000   795.750000     1.000000   
50%      9478.500000     6.000000     5.000000   991.500000     2.000000   
75%     11601.500000     7.000000     6.000000  1298.250000     2.000000   
max    215245.000000    10.000000     9.000000  6110.000000     3.000000   

          HalfBath  BedroomAbvGr  TotRmsAbvGrd   Fireplaces   GarageArea  \
count  1460.000000   1460.000000   1460.000000  1460.000000  1460.000000   
mean      0.382877      2.866438      6.517808     0.613014   472.980137   
std       0.502885      0.815778      1.625393     0.644666   213.804841   
min       0.000000      0.000000      2.000000     0.000000     0.000000   
25%       0.000000      2.000000      5.000000     0.000000   334.500000   
50%       0.000000      3.000000      6.000000     1.000000   480.000000   
75%       1.000000      3.000000      7.000000     1.000000   576.000000   
max       2.000000      8.000000     14.000000     3.000000  1418.000000   

       AboveMedianPrice  
count       1460.000000  
mean           0.498630  
std            0.500169  
min            0.000000  
25%            0.000000  
50%            0.000000  
75%            1.000000  
max            1.000000

In [ ]:
# check for null values in the dataset
df.isnull()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0       False        False        False        False     False     False   
1       False        False        False        False     False     False   
2       False        False        False        False     False     False   
3       False        False        False        False     False     False   
4       False        False        False        False     False     False   
...       ...          ...          ...          ...       ...       ...   
1455    False        False        False        False     False     False   
1456    False        False        False        False     False     False   
1457    False        False        False        False     False     False   
1458    False        False        False        False     False     False   
1459    False        False        False        False     False     False   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0            False         False       False       False             False  
1            False         False       False       False             False  
2            False         False       False       False             False  
3            False         False       False       False             False  
4            False         False       False       False             False  
...            ...           ...         ...         ...               ...  
1455         False         False       False       False             False  
1456         False         False       False       False             False  
1457         False         False       False       False             False  
1458         False         False       False       False             False  
1459         False         False       False       False             False  

[1460 rows x 11 columns]

In [ ]:
# sum of null values
df.isnull().sum()

LotArea             0
OverallQual         0
OverallCond         0
TotalBsmtSF         0
FullBath            0
HalfBath            0
BedroomAbvGr        0
TotRmsAbvGrd        0
Fireplaces          0
GarageArea          0
AboveMedianPrice    0
dtype: int64

In [ ]:
# to drop all the null values
df.dropna()

LotArea  OverallQual  OverallCond  TotalBsmtSF  FullBath  HalfBath  \
0        8450            7            5          856         2         1   
1        9600            6            8         1262         2         0   
2       11250            7            5          920         2         1   
3        9550            7            5          756         1         0   
4       14260            8            5         1145         2         1   
...       ...          ...          ...          ...       ...       ...   
1455     7917            6            5          953         2         1   
1456    13175            6            6         1542         2         0   
1457     9042            7            9         1152         2         0   
1458     9717            5            6         1078         1         0   
1459     9937            5            6         1256         1         1   

      BedroomAbvGr  TotRmsAbvGrd  Fireplaces  GarageArea  AboveMedianPrice  
0                3             8           0         548                 1  
1                3             6           1         460                 1  
2                3             6           1         608                 1  
3                3             7           1         642                 0  
4                4             9           1         836                 1  
...            ...           ...         ...         ...               ...  
1455             3             7           1         460                 1  
1456             3             7           2         500                 1  
1457             4             9           2         252                 1  
1458             2             5           0         240                 0  
1459             3             6           0         276                 0  

[1460 rows x 11 columns]

In [ ]:
df.shape

(1460, 11)

In [ ]:
# alternate way of checking for any null values
np.isnan(df.values).any()

False

In [ ]:
# selecting input feature and output label
x = df.iloc[:,0:10].values # taking first 10 colums and all rows
y = df.iloc[:,10].values  

In [ ]:
# checking the type of object
type(x)

numpy.ndarray

In [ ]:
x

array([[ 8450,     7,     5, ...,     8,     0,   548],
       [ 9600,     6,     8, ...,     6,     1,   460],
       [11250,     7,     5, ...,     6,     1,   608],
       ...,
       [ 9042,     7,     9, ...,     9,     2,   252],
       [ 9717,     5,     6, ...,     5,     0,   240],
       [ 9937,     5,     6, ...,     6,     0,   276]])

In [ ]:
y

array([1, 1, 1, ..., 1, 0, 0])

In [ ]:
# step 4: dividing into training and test dataset
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 42)

In [ ]:
# step 5: feature scaling
# convert large values to smaller value to apply regression
min_max_scaler = preprocessing.MinMaxScaler()
x_scale = min_max_scaler.fit_transform(x_train)

In [ ]:
x_scale

array([[0.0425343 , 0.66666667, 0.625     , ..., 0.41666667, 0.33333333,
        0.37376587],
       [0.01110098, 0.44444444, 0.5       , ..., 0.25      , 0.        ,
        0.37023977],
       [0.03430788, 0.66666667, 0.5       , ..., 0.41666667, 0.        ,
        0.43300423],
       ...,
       [0.0321204 , 0.44444444, 0.75      , ..., 0.25      , 0.        ,
        0.40338505],
       [0.02964313, 0.66666667, 0.875     , ..., 0.41666667, 0.33333333,
        0.15232722],
       [0.01114305, 0.66666667, 0.5       , ..., 0.41666667, 0.33333333,
        0.46544429]])

In [ ]:
# classifies the data using linear model
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:818: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG,


LogisticRegression(random_state=0)

In [ ]:
y_pred = classifier.predict(x_test)

In [ ]:
y_pred

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1,

In [ ]:
from sklearn.metrics import accuracy_score
print('Accuracy : ', accuracy_score(y_test, y_pred))

Accuracy :  0.8310502283105022


In [ ]:
# finding precision and recall
np.column_stack((y_test[:10], y_pred[:10]))

array([[0, 0],
       [1, 1],
       [0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [1, 0],
       [0, 1],
       [0, 0],
       [0, 0]])