In [2]:
# import numpy and load_loadwine
import numpy as np
from sklearn.datasets import load_wine

In [3]:
# load the dataset
wine_dataset = load_wine()

In [4]:
# get the features and the label from the dataset
wine_dataset_features = wine_dataset.data
wine_dataset_labels = wine_dataset.target

In [5]:
# printing the features and labels of the dataset
print(wine_dataset_features)
print(wine_dataset_labels)

[[1.423e+01 1.710e+00 2.430e+00 ... 1.040e+00 3.920e+00 1.065e+03]
 [1.320e+01 1.780e+00 2.140e+00 ... 1.050e+00 3.400e+00 1.050e+03]
 [1.316e+01 2.360e+00 2.670e+00 ... 1.030e+00 3.170e+00 1.185e+03]
 ...
 [1.327e+01 4.280e+00 2.260e+00 ... 5.900e-01 1.560e+00 8.350e+02]
 [1.317e+01 2.590e+00 2.370e+00 ... 6.000e-01 1.620e+00 8.400e+02]
 [1.413e+01 4.100e+00 2.740e+00 ... 6.100e-01 1.600e+00 5.600e+02]]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2]


In [34]:
# split the dataset into training and test dataset
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(wine_dataset_features, wine_dataset_labels, test_size=0.20, random_state=28)

In [35]:
# load the k-nearest neighbor classifier
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=5)
print(knn_classifier)

KNeighborsClassifier()


In [36]:
# fitting the classifier on the training dataset
knn_classifier.fit(x_train, y_train)

KNeighborsClassifier()

In [37]:
print(np.shape(x_test))

(36, 13)


In [38]:
# making the prediction with knn classifier, comparing it with ground truth and getting the score value
knn_classifier_predictions = knn_classifier.predict(x_test)

In [39]:
# calculating the accuracy and the confusion matrix
from sklearn.metrics import accuracy_score, confusion_matrix
acc = accuracy_score(knn_classifier_predictions, y_test)
cm = confusion_matrix(knn_classifier_predictions, y_test)
print(acc)
cm

0.75


array([[ 7,  0,  0],
       [ 0, 11,  1],
       [ 2,  6,  9]])

In [41]:
# getting the score of the training and testing dataset
print(knn_classifier.score(x_train, y_train))
print(knn_classifier.score(x_test, y_test))

0.7816901408450704
0.75
