In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

In [ ]:
dataset = pd.read_csv('/content/drive/MyDrive/deep_learning_bootcamp/day5/car_evaluation.csv')

In [ ]:
dataset.head()

vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [ ]:
# renaming the column dataset
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
dataset.columns = col_names

In [ ]:
dataset.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    med  unacc
1  vhigh  vhigh     2       2    small   high  unacc
2  vhigh  vhigh     2       2      med    low  unacc
3  vhigh  vhigh     2       2      med    med  unacc
4  vhigh  vhigh     2       2      med   high  unacc

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1727 non-null   object
 1   maint     1727 non-null   object
 2   doors     1727 non-null   object
 3   persons   1727 non-null   object
 4   lug_boot  1727 non-null   object
 5   safety    1727 non-null   object
 6   class     1727 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [ ]:
# to get the count of 
for col in col_names:
  print(dataset[col].value_counts())

high     432
med      432
low      432
vhigh    431
Name: buying, dtype: int64
high     432
med      432
low      432
vhigh    431
Name: maint, dtype: int64
3        432
4        432
5more    432
2        431
Name: doors, dtype: int64
4       576
more    576
2       575
Name: persons, dtype: int64
med      576
big      576
small    575
Name: lug_boot, dtype: int64
med     576
high    576
low     575
Name: safety, dtype: int64
unacc    1209
acc       384
good       69
vgood      65
Name: class, dtype: int64


In [ ]:
# checking for any missing value in the dataset
dataset.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [ ]:
# separating the dataset
X = dataset.drop(['class'], axis=1)
y = dataset['class']

In [ ]:
# split into training and testing dataset
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 20)

In [ ]:
X_train.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
dtype: object

In [ ]:
# import category encoders
!pip install category_encoders

In [ ]:
import category_encoders as ce
# ce is used to scale dataset with both string and number

In [ ]:
# encode variable with ordinal encoding
encoder = ce.OrdinalEncoder(cols=['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety'])
X_train = encoder.fit_transform(X_train)
X_test = encoder.transform(X_test)

In [ ]:
X_train.head()

buying  maint  doors  persons  lug_boot  safety
545        1      1      1        1         1       1
1570       2      2      2        1         2       2
1715       2      3      3        2         1       1
109        3      1      1        1         3       2
440        1      4      1        2         3       1

In [ ]:
# traning the dataset
# import the DecisionTreeClassifier
from sklearn.tree import DecisionTreeClassifier

In [ ]:
clf_gini = DecisionTreeClassifier(criterion='gini', max_depth=20, random_state=0)
# fit the model
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=20, random_state=0)

In [ ]:
y_pred_gini = clf_gini.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('model accuracy is: {0:0.4f}'.format(accuracy_score(y_test,y_pred_gini)))
print(confusion_matrix(y_test, y_pred_gini))

model accuracy is: 0.9596
[[117   4  12   0]
 [  1  17   0   0]
 [  5   0 397   0]
 [  0   1   0  16]]


In [ ]:
# instantiate the DecisionTreeClassifier with criteron entropy
clf_en = DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)
# fit the model
clf_en.fit(X_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=3, random_state=0)

In [ ]:
y_pred_en = clf_en.predict(X_test)

In [ ]:
from sklearn.metrics import accuracy_score, confusion_matrix
print('model accuracy is: {0:0.4f}'.format(accuracy_score(y_test,y_pred_en)))
print(confusion_matrix(y_test, y_pred_en))

model accuracy is: 0.8140
[[104   0  29   0]
 [ 18   0   0   0]
 [ 42   0 360   0]
 [ 17   0   0   0]]
